"""End-to-end Tier 2 pipeline orchestration (Step 7).

Runs Steps 1 → 6 in order for one mutation, loops Steps 5–6 over every candidate
drug, and assembles `api-contracts.md`-shaped result items.

This is the single entry point Tier 1's orchestration backend calls. Per
`tier2-implementation-spec.md` §7 the exposure surface is an **importable
function**, not an HTTP service of its own — Tier 2 stays dependency-light and
offline-testable, and Tier 1 owns the one FastAPI surface. `run_tier2` returns
plain objects; it performs no I/O beyond the pipeline steps themselves and
writes to no database.

## Design commitments

**Failures are results, never silence.** Every §8 condition returns a structured
`FailureObject` carrying the *exact* documented message. `api-contracts.md`
requires these always render in the UI, and `tier2-structural-prediction.md` §8
is explicit about why: a doctor cannot distinguish "checked, found nothing
concerning" from "silently failed," and that ambiguity is dangerous in a
clinical-adjacent tool. Nothing here returns a bare empty list or `None` to mean
failure.

**Partial results survive.** A structure failure does not discard the
AlphaMissense score, and one unscoreable candidate does not drop the rest of the
shortlist. `Tier2Output` carries results and failures side by side.

**`delta_score` and `label` are optional in the internal model.** Per
`tier2-implementation-spec.md` §6, a candidate with a real evidence trail and no
computable binding delta is a legitimate future output shape (non-small-molecule
modalities cannot be scored by mCSM-lig or Vina at all). Such candidates surface
as failure objects today rather than as malformed result items, but nothing here
assumes every candidate must have a delta.

**The disclaimer is one constant.** `api-contracts.md` requires it be identical
on every item and sourced from a single shared constant, never re-typed per call
site — hence `DISCLAIMER` below, attached in exactly one place.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Literal

from secondlook.alphamissense import AlphaMissenseResult, lookup_alphamissense
from secondlook.binding import BindingScore, score_binding
from secondlook.candidates import (
    ZERO_CANDIDATES_MESSAGE,
    CandidateResult,
    DrugCandidate,
    generate_candidates,
)
from secondlook.graph import PIPELINE_VERSION, StructuralSignal, utc_now_iso
from secondlook.labeling import (
    MethodCalibration,
    ScoringMethod,
    label_binding_delta,
)
from secondlook.mutation_validation import (
    MutationValidationResult,
    validate_mutation,
)
from secondlook.proximity import ProximitySignal, build_proximity_signal
from secondlook.structure import StructureResult, source_structure
from secondlook.tier1_contract import ActivationDecision, ActivationPolicy, GraphSink
from secondlook.uniprot import UniProtLookupError

#: The fixed §10 disclaimer, verbatim from `tier2-structural-prediction.md`.
#: THE single source of this text — attach it by reference, never by retyping.
DISCLAIMER = (
    "This is a computational plausibility signal generated by structural prediction "
    "tools for research and hypothesis-generation only. It is not clinical evidence, "
    "a diagnosis, or a treatment recommendation, and it has not been clinically "
    "validated for this mutation. The underlying models predict physical "
    "binding/stability changes with limited accuracy and were not designed to predict "
    "patient response. These results must be interpreted by a qualified clinician "
    "alongside established evidence before any clinical decision. Do not use this "
    "output to start, stop, or change any treatment."
)

#: §8 "Timeout / external API error". The other §8 messages already live next to
#: the module that raises them; this one is orchestration-level, so it lives here.
PIPELINE_ERROR_MESSAGE = (
    "Tier 2 analysis could not complete (timeout/error). No partial or inferred result "
    "is shown to avoid misleading output. Please retry or consult evidence-based resources."
)

Tier2Status = Literal["complete", "partial", "failed", "not_run"]

#: The exact fields `api-contracts.md` defines for "Mutation validator output".
#: `MutationValidationResult` also carries `wildtype_sequence`/`mutant_sequence`
#: as internal working state; those are **not** part of the contract and must not
#: ride along on every result item — for a real protein that is two full sequences
#: duplicated per candidate, and neither is useful to the UI.
_MUTATION_CONTRACT_FIELDS = (
    "status",
    "gene",
    "hgvs_normalized",
    "uniprot_accession",
    "isoform_note",
    "position",
    "reference_residue_expected",
    "reference_residue_actual",
    "mutation_type",
    "error_message",
)


def mutation_validated_payload(validation: MutationValidationResult) -> dict:
    """Render a validated mutation as the documented contract shape, nothing more."""
    return {field: getattr(validation, field) for field in _MUTATION_CONTRACT_FIELDS}


@dataclass(frozen=True)
class FailureObject:
    """`api-contracts.md` failure/empty-state object, always rendered by the UI."""

    reason: str
    retryable: bool
    #: Which pipeline step produced this, for debugging. Not part of the wire contract.
    step: str | None = None
    type: Literal["failure"] = "failure"
    tier: Literal["2"] = "2"

    def to_dict(self) -> dict:
        return {
            "type": self.type,
            "tier": self.tier,
            "reason": self.reason,
            "retryable": self.retryable,
        }


@dataclass(frozen=True)
class Tier2ResultItem:
    """One scored candidate, matching `api-contracts.md` "Tier 2 result item"."""

    mutation_validated: dict
    alphamissense: dict
    structure: dict
    drug: str
    smiles_source: str | None
    #: None when no defensible binding delta exists — see `signal_type`.
    method: ScoringMethod | None
    delta_score: float | None
    label: str | None
    binding_site_distance_angstrom: float | None
    #: Measured binding-site proximity. Present whenever an experimental structure
    #: with a bound drug was available, independent of whether a delta was computed.
    proximity: dict
    #: "binding_delta" — a delta and label are present.
    #: "proximity_only" — the mutation's position relative to the drug pocket is
    #: reported, with no binding-change prediction. Per `validation-plan.md`'s
    #: fallback clause, this is the honest output shape wherever the gold-standard
    #: run did not support a delta.
    signal_type: Literal["binding_delta", "proximity_only"]
    disclaimer: str
    # Honesty metadata beyond the base contract. Required by
    # `tier2-implementation-spec.md` §1.3 item 6: an mCSM-lig label and a docking
    # label must not be presented with equivalent confidence.
    confidence: str | None
    calibration_status: str | None
    accuracy_note: str | None
    heuristic_note: str | None
    delta_score_unit: str | None
    type: Literal["computational_signal"] = "computational_signal"

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class Tier2Output:
    """Everything one Tier 2 run produced."""

    status: Tier2Status
    results: list[Tier2ResultItem] = field(default_factory=list)
    failures: list[FailureObject] = field(default_factory=list)
    #: Graph-ready nodes for Tier 1 to persist (see `graph.py`).
    signals: list[StructuralSignal] = field(default_factory=list)
    #: Reported even when the pipeline later fails — §8's structure-unavailable
    #: message explicitly promises AlphaMissense as the remaining signal.
    alphamissense: AlphaMissenseResult | None = None
    validation: MutationValidationResult | None = None
    structure: StructureResult | None = None
    activation: ActivationDecision | None = None
    computed_at: str = ""
    pipeline_version: str = PIPELINE_VERSION

    @property
    def scored_by_method(self) -> dict[str, int]:
        """Counts per scoring method.

        Feeds the mCSM-lig-vs-docking coverage ratio that
        `tier2-implementation-spec.md` §5 deliverable 5 requires be reported
        honestly rather than assumed.
        """
        counts: dict[str, int] = {}
        for item in self.results:
            key = item.method if item.method is not None else "null"
            counts[key] = counts.get(key, 0) + 1
        return counts


def run_tier2(
    gene: str,
    mutation: str,
    *,
    cancer_type: str | None = None,
    activation_policy: ActivationPolicy | None = None,
    graph_sink: GraphSink | None = None,
    calibrations: dict[ScoringMethod, MethodCalibration] | None = None,
    max_candidates: int | None = None,
    restrict_to_drugs: tuple[str, ...] | None = None,
    sequence_provider=None,
    transcript_resolver=None,
    vep_client=None,
    pdb_client=None,
    alphafold_client=None,
    esm_client=None,
    dgidb_client=None,
    opentargets_client=None,
    chembl_client=None,
    pubchem_client=None,
    mcsm_client=None,
    vina_client=None,
    het_resolver=None,
    min_delay_seconds: float = 3.0,
    sleeper=None,
) -> Tier2Output:
    """Run the full Tier 2 pipeline for one gene + mutation.

    Every client is injectable, matching the existing module convention — the
    defaults hit live services, and tests pass fakes. `calibrations` overrides
    the Step 6 thresholds so the validation harness can sweep cutoffs without
    mutating module state.
    """
    computed_at = utc_now_iso()

    activation = None
    if activation_policy is not None:
        activation = activation_policy.decide(gene=gene, mutation=mutation, cancer_type=cancer_type)
        if not activation.should_run_tier2:
            return Tier2Output(
                status="not_run",
                activation=activation,
                computed_at=computed_at,
            )

    # --- Steps 0 & 1: scope gate + mutation validation ----------------------
    # UniProt is the one external call with no fallback source, so its failure is
    # the pipeline's own to report. Every other step already resolves its errors
    # internally (structure falls through RCSB -> AlphaFold, candidates through
    # DGIdb -> Open Targets -> ChEMBL, AlphaMissense to an "unavailable" result).
    # Caught specifically, never as a bare `except`.
    try:
        validation = validate_mutation(gene, mutation, sequence_provider=sequence_provider)
    except UniProtLookupError:
        return Tier2Output(
            status="failed",
            failures=[
                FailureObject(
                    reason=PIPELINE_ERROR_MESSAGE,
                    retryable=True,
                    step="mutation_validation",
                )
            ],
            activation=activation,
            computed_at=computed_at,
        )
    if validation.status != "valid":
        # Reuses the exact §8 message the validator already produced. Neither
        # condition is retryable: retrying an isoform mismatch or an out-of-scope
        # variant type produces the identical answer.
        return Tier2Output(
            status="failed",
            failures=[
                FailureObject(
                    reason=validation.error_message or PIPELINE_ERROR_MESSAGE,
                    retryable=False,
                    step="mutation_validation",
                )
            ],
            validation=validation,
            activation=activation,
            computed_at=computed_at,
        )

    # --- Step 2: AlphaMissense (informational; never gates the pipeline) -----
    alphamissense = lookup_alphamissense(
        validation,
        transcript_resolver=transcript_resolver,
        vep_client=vep_client,
    )

    # --- Step 3: structure sourcing -----------------------------------------
    structure = source_structure(
        validation,
        pdb_client=pdb_client,
        alphafold_client=alphafold_client,
        esm_client=esm_client,
    )
    if structure.status != "found":
        # Retryable: this covers transient RCSB/AlphaFold outages as well as
        # genuinely absent structures, and the caller cannot tell them apart.
        return Tier2Output(
            status="partial",
            failures=[
                FailureObject(
                    reason=structure.error_message or PIPELINE_ERROR_MESSAGE,
                    retryable=True,
                    step="structure",
                )
            ],
            alphamissense=alphamissense,
            validation=validation,
            structure=structure,
            activation=activation,
            computed_at=computed_at,
        )

    # --- Step 4: candidate drug generation ----------------------------------
    candidate_kwargs = {
        "dgidb_client": dgidb_client,
        "opentargets_client": opentargets_client,
        "chembl_client": chembl_client,
        "pubchem_client": pubchem_client,
    }
    if max_candidates is not None:
        candidate_kwargs["max_candidates"] = max_candidates
    candidates: CandidateResult = generate_candidates(validation, **candidate_kwargs)
    if restrict_to_drugs:
        # Score only these drugs from the generated shortlist. Used by the
        # gold-standard harness, which tests *directionality on a known
        # variant-drug pair* — the pair must still be produced by Step 4, so this
        # narrows the shortlist rather than bypassing candidate generation. Also
        # keeps the run affordable: each candidate costs two real docking runs.
        wanted = {name.strip().lower() for name in restrict_to_drugs}
        kept = [c for c in candidates.candidates if c.name.strip().lower() in wanted]
        candidates = CandidateResult(
            status="found" if kept else "none",
            candidates=kept,
            error_message=None if kept else ZERO_CANDIDATES_MESSAGE,
        )
    if candidates.status != "found" or not candidates.candidates:
        return Tier2Output(
            status="partial",
            failures=[
                FailureObject(
                    reason=candidates.error_message or ZERO_CANDIDATES_MESSAGE,
                    retryable=False,
                    step="candidates",
                )
            ],
            alphamissense=alphamissense,
            validation=validation,
            structure=structure,
            activation=activation,
            computed_at=computed_at,
        )

    # --- Steps 5 & 6: score and label every candidate -----------------------
    results: list[Tier2ResultItem] = []
    failures: list[FailureObject] = []
    signals: list[StructuralSignal] = []

    proximity = measure_proximity(structure, validation.position)

    for candidate in candidates.candidates:
        binding = score_binding(
            validation,
            structure,
            candidate,
            mcsm_client=mcsm_client,
            vina_client=vina_client,
            het_resolver=het_resolver,
            min_delay_seconds=min_delay_seconds,
            sleeper=sleeper,
        )
        item, signal, failure = _assemble_candidate(
            validation=validation,
            alphamissense=alphamissense,
            structure=structure,
            candidate=candidate,
            binding=binding,
            calibrations=calibrations,
            computed_at=computed_at,
            proximity=proximity,
        )
        if failure is not None:
            failures.append(failure)
        if item is not None:
            results.append(item)
        if signal is not None:
            signals.append(signal)

    if graph_sink is not None:
        for signal in signals:
            graph_sink.emit(signal)

    if results:
        status: Tier2Status = "complete" if not failures else "partial"
    else:
        status = "partial"

    return Tier2Output(
        status=status,
        results=results,
        failures=failures,
        signals=signals,
        alphamissense=alphamissense,
        validation=validation,
        structure=structure,
        activation=activation,
        computed_at=computed_at,
    )


def measure_proximity(structure: StructureResult, position: int | None) -> ProximitySignal:
    """Measure how far the mutated residue sits from the bound drug.

    Independent of docking: it needs only experimental coordinates with a
    co-crystallized ligand, so it is available on cases where no binding delta is.
    Falls back to an "unknown" band rather than guessing.
    """
    distance = None
    ligand_id = None
    if position is not None and structure.pdb_text:
        from secondlook.vina_dock import (
            NoBindingSiteError,
            extract_chain,
            residue_ligand_distance,
            select_docking_chain,
        )

        try:
            chain = select_docking_chain(structure.pdb_text, position)
        except NoBindingSiteError:
            chain = None
        if chain is not None:
            distance, ligand_id = residue_ligand_distance(
                extract_chain(structure.pdb_text, chain), position
            )
    return build_proximity_signal(
        distance,
        structure_id=structure.id,
        structure_source=structure.source,
        measured_to_ligand=ligand_id,
    )


def _assemble_candidate(
    *,
    validation: MutationValidationResult,
    alphamissense: AlphaMissenseResult,
    structure: StructureResult,
    candidate: DrugCandidate,
    binding: BindingScore,
    calibrations: dict[ScoringMethod, MethodCalibration] | None,
    computed_at: str,
    proximity: ProximitySignal,
) -> tuple[Tier2ResultItem | None, StructuralSignal | None, FailureObject | None]:
    """Turn one scored candidate into (result item, graph signal, failure).

    Three outcomes, in decreasing strength:
      1. a binding delta was computed  -> full item, `signal_type="binding_delta"`
      2. no delta but proximity measured -> `signal_type="proximity_only"`
      3. neither                          -> a failure object

    Case 2 is the `validation-plan.md` fallback made concrete: a real, measured
    result rather than an absence, so the UI has something true to show wherever a
    delta is not defensible.
    """
    proximity_payload = {
        "band": proximity.band,
        "distance_angstrom": proximity.distance_angstrom,
        "description": proximity.description,
        "contact_mechanism_available": proximity.contact_mechanism_available,
        # Named so a reader can see the distance is to this ligand, not to the
        # candidate drug — unless ligand_is_candidate_drug says otherwise.
        "measured_to_ligand": proximity.measured_to_ligand,
        "ligand_is_candidate_drug": proximity.ligand_is_candidate_drug,
    }

    scored = (
        binding.status == "scored"
        and binding.delta_score is not None
        and binding.method is not None
    )

    if not scored and proximity.band == "unknown":
        retryable = binding.reason_code not in ("outside_pocket", "mechanism_invalidated")
        return (
            None,
            None,
            FailureObject(
                reason=binding.error_message or PIPELINE_ERROR_MESSAGE,
                retryable=retryable,
                step=f"binding:{candidate.name}",
            ),
        )

    labeled = None
    if scored:
        calibration = calibrations.get(binding.method) if calibrations else None
        labeled = label_binding_delta(binding.delta_score, binding.method, calibration=calibration)

    item = Tier2ResultItem(
        mutation_validated=mutation_validated_payload(validation),
        alphamissense={
            "score": alphamissense.am_pathogenicity,
            "class": alphamissense.am_class,
        },
        structure={
            "source": structure.source,
            "id": structure.id,
            "plddt_at_residue": structure.plddt_at_residue,
            "reliability_flag": structure.reliability_flag,
        },
        drug=candidate.name,
        smiles_source=candidate.smiles_source,
        method=binding.method if scored else None,
        delta_score=binding.delta_score if scored else None,
        label=labeled.label if labeled else None,
        binding_site_distance_angstrom=proximity.distance_angstrom,
        proximity=proximity_payload,
        signal_type="binding_delta" if scored else "proximity_only",
        disclaimer=DISCLAIMER,
        confidence=labeled.confidence if labeled else None,
        calibration_status=labeled.calibration_status if labeled else None,
        accuracy_note=labeled.accuracy_note if labeled else None,
        heuristic_note=labeled.heuristic_note if labeled else None,
        delta_score_unit=labeled.unit if labeled else None,
    )

    signal = StructuralSignal(
        gene=validation.gene or "",
        hgvs_p=validation.hgvs_normalized or "",
        drug=candidate.name,
        alphamissense_score=alphamissense.am_pathogenicity,
        alphamissense_class=alphamissense.am_class,
        structure_source=structure.source,
        structure_id=structure.id,
        plddt_at_residue=structure.plddt_at_residue,
        reliability_flag=structure.reliability_flag,
        method=binding.method if scored else None,
        delta_score=binding.delta_score if scored else None,
        label=labeled.label if labeled else None,
        binding_site_distance_angstrom=proximity.distance_angstrom,
        confidence=labeled.confidence if labeled else None,
        calibration_status=labeled.calibration_status if labeled else None,
        computed_at=computed_at,
        pipeline_version=PIPELINE_VERSION,
        labeling_version=labeled.labeling_version if labeled else None,
    )

    return item, signal, None
